<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tva;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Query\Expr;

/**
 * TvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPage($page, $nbParPage)
    {

        $query = $this->getEntityManager()->createQuery("SELECT T FROM AppBundle:Tva T")
            ->setFirstResult($page)
            ->setMaxResults($nbParPage)
        ;
        $query->execute();

        return $query->getResult();
    }
}
